### ISSUE TITLE
pre-provision vms to include python2 before saltstack bootstrap is run

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#297]
i just found out that ubuntu-16-04 does not ship with python 2. maybe it used to in like 16.04.3

the saltstack bootstrap file needs python2. salt does not support python3 yet.

I need to rebuild these boxes

https://www.theshell.guru/install-apache-python-on-ubuntu-16-04-lts/

we should also pre-install python 2 for docker and ec2

**Comment by verhulstm** [comment]
see pr ##298

**Comment by nixjdm** [comment]
Salt does work with Python3: https://github.com/saltstack/salt/issues/11995.

I also would have expected the bootstrapper to be pretty resilient, and appears to be. It's mostly (all?) a shell script itself. Despite the above link, it looks like for Ubuntu 16 the bootstrapper installs python2.7 anyway for you already: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2631-L2633.

So for two reasons I wouldn't think there'd be a problem.

I'm also pretty sure all Ubuntu 16 ISOs come without Python2. Anecdotally, the box that we've been hosting and using for a while, `terminal-labs/tl-ubuntu-1604-64bit-30gb (virtualbox, 0.1)`, doesn't come with Python2, but it's been working fine for as long as we've had it.

Are you seeing an error? What brought this up?

**Comment by nixjdm** [comment]
I just upgraded boxes (now `terminal-labs/tl-ubuntu-1604-64bit-30gb (virtualbox, 0.2)` which is 16.04.4) and saw no change - everything still works.

You can prove to yourself that the bootstrapper installs Python2.7 by running `rambo up --no-provision`, and SSHing in and seeing that Python2.7 is absent, and then removing the top.sls file and running `rambo halt; rambo up --provision` to run the bootstrapper but no states. Then you'll find Python2.7 installed.

**Comment by verhulstm** [comment]
I found this issue last night. I reproduced the issue about 10 times on my laptop. the bootstrap file was not installing python2.7. 

The boostrap file said it had an error with "line #9, python not found"

**Comment by verhulstm** [comment]
I fixed the problem. my laptop had vagrant version 1.9.7. updating to v2.0.2 solved it.

Looks like v1.9.7 reset some env vars incorrectly such that when vagrant downloaded the saltbootstrape file it could not install python 2.7.

but, you could manually install saltstack and the bootstrap file would then be able to pre-install python

**Comment by verhulstm** [comment]
we can close this

**Comment by nixjdm** [comment]
You don't happen to still have the full error, do you? I'm only trying to guess what actually threw that error. Something called by the bootstrapper perhaps, but not the bootstrapper itself? The first many lines of the shell script are just comments.

If Vagrant 1.9.7 really was the problem, I'd like to confirm that so we can bump this. https://github.com/terminal-labs/rambo/blob/master/rambo/Vagrantfile#L38

**Comment by verhulstm** [comment]
min working version is vagrant v2.0.1

**Comment by verhulstm** [comment]
here is the error output:

Checking if salt-minion is installed
salt-minion was not found.
Checking if salt-call is installed
salt-call was not found.
Using Bootstrap Options:  -P
Bootstrapping Salt... (this may take a while)
/tmp/bootstrap_salt.sh: 9: /tmp/bootstrap_salt.sh:
python: not found

Salt successfully installed!
run_overstate set to false. Not running state.overstate.
run_highstate set to false. Not running state.highstate.
orchestrate is nil. Not running state.orchestrate.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mv: 
==> default: cannot stat '/etc/salt/minion'
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file '/etc/salt/minion'
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file '/etc/salt/grains'
==> default: : No such file or directory
==> default: sudo
==> default: : 
==> default: salt-call: command not found
==> default: sudo
==> default: : 
==> default: salt-call: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
